# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title : "Edwin Rodríguez"
tagline: "Software engineer"
description: "I'm a enthusiast software engineer interested is many topics like development, phylosophy, science and art. Here are my blog, projects and contact information."
image: "/img/meta-img.jpg"

author :
  name : "Edwin Rodríguez"
  email : "edwrodrig@gmail.com"
  services:
    facebook: edwrodrig
    youtube: edwrodrig
    twitter: edwrodrig

production_url : http://edwrodrig.github.io
google_tracking_id : "UA-49580762-2"

type:
  name: "normal"
  github_project:
    user: ""
    name: ""

sharing:
  - "facebook"
  - "twitter"
  - "google-plus"

markdown: kramdown
