# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
debug: debug

title : "Edwin Rodríguez"
tagline: "Software engineer"
description: "I'm a enthusiast software engineer interested is many topics like development, phylosophy, science and art. Here are my blog, projects and contact information."
image: "/img/meta-img.jpg"

author :
  name : "Edwin Rodríguez"
  email : "edwrodrig@gmail.com"
  page: "http://edwrodrig.github.io"
  services:
    facebook: edwrodrig
    youtube: edwrodrig
    twitter: edwrodrig

production_url : http://edwrodrig.github.io/mmmm
google_tracking_id : "UA-49580762-2"

type:
  name: "github_project"
  github_project:
    user: "edwrodrig"
    name: "edwrodrig.github.io"

sharing:
  style: "native"
  services:
    - "facebook"
    - "twitter"
    - "google-plus"
    - "pinterest"
    - "github"

markdown: kramdown
