permalink: /:categories/:year/:month/:day/:title 

exclude: ["README.md"]
pygments: true

title : "Edwin Rodríguez"
tagline: "Software engineer"
description: "I'm a enthusiast software engineer interested is many topics like development, phylosophy, science and art. Here are my blog, projects and contact information."
image: "/img/meta-img.jpg"

author :
  name : "Edwin Rodríguez"
  email : "edwrodrig@gmail.com"
  page: "http://edwrodrig.github.io"
  services:
    twitter: edwrodrig

production_url : http://edwrodrig.github.io
google_tracking_id : "UA-49580762-2"

type:
  name: "normal"
  github_project:
    user: "edwrodrig"
    name: "edwrodrig.github.io"

sharing:
  style: "native"
  services:
    - "facebook"
    - "twitter"
    - "google-plus"
    - "pinterest"

markdown: kramdown
